name: deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node 👀
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '12.x'
      - run: npm install

      - name: Cache dependencies 🌵
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: npm run export

      - name: Post Build 🛸
        run: |
            sed -i 's/<base href=\/ >/<base href=\/pingpong\/ >/g' ./__sapper__/export/pingpong/index.html
            cat ./__sapper__/export/pingpong/index.html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: __sapper__/export/pingpong
