name: deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node 👀
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '12.x'
      - run: npm install

      - name: Cache dependencies 🌵
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: npm run export
        env:
          BASE_PATH: pixi-pack

      - name: Post Build 🛸 (fix Sapper bug of not using proper basePath)
        run: |
            sed -i 's/<base href=\/ >/<base href=\/pixi-pack\/ >/g' ./__sapper__/export/pixi-pack/index.html
            sed -i 's/src="\/client\//src="\/pixi-pack\/client\//g' ./__sapper__/export/pixi-pack/index.html
            sed -i 's/"data-main","\/client/"data-main","\/pixi-pack\/client/g' ./__sapper__/export/pixi-pack/index.html
            sed -i "s/'\/service-worker.js'/'\/pixi-pack\/service-worker.js'/g" ./__sapper__/export/pixi-pack/index.html
            sed -i 's/"\//"\/pixi-pack\//g' ./__sapper__/export/pixi-pack/service-worker.js
            sed -i 's/<base href=\/ >/<base href=\/pixi-pack\/ >/g' ./__sapper__/export/pixi-pack/service-worker-index.html
            sed -i 's/src="\/client\//src="\/pixi-pack\/client\//g' ./__sapper__/export/pixi-pack/service-worker-index.html
            sed -i 's/"data-main","\/client/"data-main","\/pixi-pack\/client/g' ./__sapper__/export/pixi-pack/service-worker-index.html
            sed -i "s/'\/service-worker.js'/'\/pixi-pack\/service-worker.js'/g" ./__sapper__/export/pixi-pack/service-worker-index.html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: __sapper__/export/pixi-pack
